CREATE TABLE [dbo].[TADDRESSINFO] (
    [ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [ADDRESS]  NVARCHAR (500) NULL,
    [PROVINCE] NVARCHAR (50)  NULL,
    [COUNTRY]  NVARCHAR (50)  NULL,
    CONSTRAINT [PK_TADDRESSINFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

