CREATE TABLE [dbo].[TBOQSETTING] (
    [BOQID]       BIGINT        NULL,
    [CODE]        NVARCHAR (50) NULL,
    [DESCRIPTION] NVARCHAR (50) NULL,
    [TYPE]        NVARCHAR (50) NULL,
    [CATEGORY]    NVARCHAR (50) NULL,
    [VALUE]       NVARCHAR (50) NULL,
    [VALUEAS]     NVARCHAR (50) NULL,
    [isACT]       TINYINT       NULL
);

