CREATE TABLE [dbo].[TDIVISION] (
    [ID]          BIGINT         NULL,
    [CDT]         DATETIME       CONSTRAINT [DF_TDIVISION_CDT] DEFAULT (getdate()) NULL,
    [MDT]         DATETIME       CONSTRAINT [DF_TDIVISION_MDT] DEFAULT (getdate()) NULL,
    [EDSEQ]       INT            CONSTRAINT [DF_TDIVISION_EDSEQ] DEFAULT ((0)) NULL,
    [DIVNAME]     NVARCHAR (50)  NULL,
    [DESCRIPTION] NVARCHAR (250) NULL,
    [ISACTIVE]    TINYINT        NULL
);

