CREATE TABLE [dbo].[TSITE] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [CDT]         DATETIME       CONSTRAINT [DF_TSITE_CDT] DEFAULT (getdate()) NULL,
    [MDT]         DATETIME       CONSTRAINT [DF_TSITE_MDT] DEFAULT (getdate()) NULL,
    [EDSEQ]       INT            CONSTRAINT [DF_TSITE_EDSEG] DEFAULT ((0)) NULL,
    [SITENAME]    NVARCHAR (50)  NULL,
    [DESCRIPTION] NVARCHAR (250) NULL,
    [ADDRESSID]   BIGINT         NULL,
    [CUSTOMERID]  BIGINT         NULL,
    [ISACTIVE]    TINYINT        CONSTRAINT [DF_TSITE_ISACTIVE] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_TSITE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

