CREATE TABLE [dbo].[TUOM] (
    [ID]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [CDT]          DATETIME      CONSTRAINT [DF_TUOM_CDT] DEFAULT (getdate()) NULL,
    [MDT]          DATETIME      CONSTRAINT [DF_TUOM_MDT] DEFAULT (getdate()) NULL,
    [EDSEQ]        INT           CONSTRAINT [DF_TUOM_EDSEQ] DEFAULT ((0)) NULL,
    [UOMNAME]      NVARCHAR (50) NULL,
    [ABBREVIATION] NCHAR (5)     NULL,
    [ISACTIVE]     TINYINT       CONSTRAINT [DF_TUOM_ISACTIVE] DEFAULT ((1)) NULL,
    [TYPE]         NVARCHAR (50) NULL,
    CONSTRAINT [PK_TUOM] PRIMARY KEY CLUSTERED ([ID] ASC)
);

