CREATE PROCEDURE [dbo].[ITEM_INSERT]
	@ITEMNAME NVARCHAR(100), 
	@DESCRIPTION NVARCHAR(400), 
	@ITEMTYPE NVARCHAR(100),
	@UOMID bigint,
	@COST decimal(18,5),
	@ISRATE BIT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
    -- Insert statements for procedure here
	INSERT INTO TITEM(ITEMNAME, DESCRIPTION, ITEMTYPE,UOMID,COST,ISRATE)
	VALUES(@ITEMNAME,@DESCRIPTION, @ITEMTYPE,@UOMID,@COST,@ISRATE)
	SELECT SCOPE_IDENTITY();
END