CREATE PROCEDURE [dbo].[SP_BoqItemLineInert]
	@BoqItemLine udt_BoqItemLine_Insert READONLY
AS
BEGIN
	INSERT INTO TBOQITEMLINE(BOQITEMID,BOQITEMLINEID,BOQITEMLINESEQ,BOQITEMLINEUOMID,BOQITEMLINEQTY)

	SELECT BOQITEMID,BOQITEMLINEID,BOQITEMLINESEQ,BOQITEMLINEUOMID,BOQITEMLINEQTY 

	FROM @BoqItemLine;

END